handlers=java.util.logging.ConsoleHandler
.level=INFO
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
com.cascada.cache.application.service.FrameMergeService.level=FINE
com.cascada.cache.adapter.out.cache.ValkeyCacheBackendAdapter.level=FINE
com.cascada.spark.adapter.out.spark.SparkDeltaQueryExecutor.level=FINE
